apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}
  labels:
{{ include "..labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 4569
      targetPort: 4569
      protocol: TCP
      name: dynamodb
    - port: 4570
      targetPort: 4570
      protocol: TCP
      name: dynamodbstreams
    - port: 4572
      targetPort: 4572
      protocol: TCP
      name: s3
    - port: 4574
      targetPort: 4574
      protocol: TCP
      name: lambda
    - port: 4576
      targetPort: 4576
      protocol: TCP
      name: sqs                     
  selector:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
